name: todo_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  get_storage: ^2.0.3
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  lottie: ^1.2.1
  google_fonts: ^3.0.1
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.2
  rxdart: ^0.27.2
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/lottie/